Zeufack
appium/appium-inspector pull request #1000
Opened 2023-07-25 19:17 UTC by zeufack

Update java code generator framework 

-change Mobile Element to Web Element

- Change Touch Action to use Sequence

2023-07-25 22:23 UTC, jlipps requested changes
thank you! I appreciate these changes! I think I found a couple errors. Can you actually get this generated code and then run it in Java / JS to make sure it compiles and runs correctly?

2023-07-25 22:23 UTC, jlipps commented on app/renderer/lib/client-frameworks/java.js
> +    driver.perform(Arrays.asList(swipe))
should `swipe` be `sequence` here?

2023-07-25 22:23 UTC, jlipps commented on app/renderer/lib/client-frameworks/java.js
> +    Sequence swipe = New  Sequence(FINGER, 1)
`New` should not be capitalized

2023-07-25 22:23 UTC, jlipps commented on target/npmlist.json
> +{"version":"2023.7.1","name":"appium-inspector","dependencies":{"@reduxjs/toolkit":{"version":"1.9.5"},"@xmldom/xmldom":{"version":"0.8.10"},"antd":{"version":"4.24.12"},"bluebird":{"version":"3.7.2"
this file should not be committed

2023-08-03 17:37 UTC, jlipps requested changes

2023-08-03 17:37 UTC, jlipps commented on app/renderer/lib/client-frameworks/java.js
> +          return new URL("http://127.0.0.1:4723");
the server and port information should not be hardcoded

2023-08-03 17:37 UTC, jlipps commented on target/npmlist.json
> +{"version":"2023.7.1","name":"appium-inspector","dependencies":{"@reduxjs/toolkit":{"version":"1.9.5"},"@xmldom/xmldom":{"version":"0.8.10"},"antd":{"version":"4.24.12"},"bluebird":{"version":"3.7.2"
please remove this file from your changeset

2023-08-04 06:54 UTC, eglitise requested changes
The file `target/npmlist.json` still exists and should be removed

2023-08-04 11:12 UTC, eglitise commented
Simply delete the `target` folder in your local workspace and commit that action.

2023-08-09 20:11 UTC, zeufack commented
> Simply delete the `target` folder in your local workspace and commit that action.

2023-08-09 20:59 UTC, jlipps approved these changes

2023-08-09 20:59 UTC, merged

2023-08-09 20:59 UTC, jlipps commented
thanks @zeufack !

2023-08-09 21:07 UTC, zeufack commented
oh, it's me who thanks you
I can't wait to work on other subjects