fix: add connection retry timeout
appium/appium-inspector pull request #442
Opened 2022-05-27 16:26 UTC by dpgraham

The connection retry timeout we have currently is too short for some cloud providers.

2022-05-27 20:50 UTC, wswebcreation commented
@dpgraham 

I think you should now remove https://github.com/appium/appium-inspector/blob/0b30b91e76dd1bb5d22f6cfd96c4310d152e0b63/app/renderer/actions/Session.js#L517
This has no value

2022-06-29 07:31 UTC, KazuCocoa approved these changes
lgtm

2022-06-30 17:01 UTC, jlipps requested changes

2022-06-30 17:01 UTC, jlipps commented on app/renderer/actions/Session.js
> +      connectionRetryTimeout: 10 * 60 * 1000,
let's put magic constants up top with a descriptive variable name.

and we're sure we want to make it a 10 minute connection timeout in all cases, not just the cloud provider case? not sure this makes sense for local servers.

2023-04-04 22:39 UTC, jlipps commented
closing due to no response and conflicts

2023-04-04 22:39 UTC, closed without merging