Adjustments for Italian language
appium/appium-inspector pull request #591
Opened 2022-09-01 15:14 UTC by giacomofuria

Hi! 

As I did [here](https://github.com/appium/appium-gui-libs/pull/7) I am making adjustments to show appium-inspector in Italian language. In this PR I've added the key 'it' in each translations.json file and added a new Key 'JSON Representation' in italian translations.json file.

2022-09-02 08:28 UTC, KazuCocoa commented
Thank you.

Could you add the diff in assets/locales/en/translation.json in appium-desktop repo?
https://github.com/appium/appium-desktop/blob/5dfb57f5ccbcc6f479fca0ab2c633e66d37238a3/CONTRIBUTING.md#localization
Other languages will be managed by crowdin, so you do not need to update them.

2022-09-27 06:56 UTC, KazuCocoa commented on app/main/menus.js
> +    label: i18n.t('New Session Window…'),
Maybe does `&` need to be the same as https://github.com/appium/appium-gui-libs/pull/7 ?

2022-09-27 22:56 UTC, jlipps requested changes

2022-09-27 22:56 UTC, jlipps commented on assets/locales/en/translation.json
> +  "it":"Italiano",
changing things here will have no effect. these values are copied over from appium desktop (it's weird, i know, and we should probably change the way this works). so you'll need to make a PR to appium desktop first with these changes.

2022-10-17 01:05 UTC, KazuCocoa commented
Added `it` in https://github.com/appium/appium-desktop/pull/2117 ad a minimal update

2022-10-17 01:05 UTC, closed without merging